import{a as g,i as a,S as L}from"./assets/vendor-NWtv_cg6.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();async function f(o,e=1,s=15){const n="https://pixabay.com/api/",t=new URLSearchParams({key:"45077635-6eb8c9a3980485254b901d63b",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:s});try{return(await g.get(`${n}?${t}`)).data}catch(r){iziToast.error({title:"Error",message:r.message,position:"center"})}}function m(o){const e=document.querySelector(".gallery"),s=o.map(n=>`<li>
                <a href="${n.largeImageURL}">
                  <img src="${n.webformatURL}" alt="${n.tags}" loading="lazy" />
                </a>
                <ul class="info">
                  <li><span>Likes:</span> ${n.likes}</li>
                  <li><span>Views:</span> ${n.views}</li>
                  <li><span>Comments:</span> ${n.comments}</li>
                  <li><span>Downloads:</span> ${n.downloads}</li>
                </ul>
              </li>`).join("");e.insertAdjacentHTML("beforeend",s)}const b=document.querySelector("#search-form"),p=document.querySelector(".gallery"),d=document.querySelector("#loader-top"),u=document.querySelector("#loader-bottom"),i=document.querySelector(".js-load-more-btn");let h,c=1,y="";b.addEventListener("submit",v);i.addEventListener("click",S);async function v(o){o.preventDefault();const e=o.target.elements.query.value.trim();if(e===""){a.info({message:"Search query cannot be empty!",position:"center"});return}p.innerHTML="",d.classList.remove("hidden"),i.classList.add("hidden"),c=1;try{const s=await f(e,c);if(d.classList.add("hidden"),s.hits.length===0){a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"center"});return}m(s.hits),h=new L(".gallery a"),h.refresh(),s.hits.length<15?(i.classList.add("hidden"),a.info({message:"You've reached the end of search results.",position:"topRight"})):i.classList.remove("hidden"),c+=1,y=e}catch(s){d.classList.add("hidden"),a.error({title:"Error",message:s.message,position:"center"})}}async function S(o){o.preventDefault(),u.classList.remove("hidden"),i.classList.add("hidden");try{const e=await f(y,c);m(e.hits),h.refresh(),c+=1,c*15>=e.totalHits||e.hits.length<15?(i.classList.add("hidden"),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):i.classList.remove("hidden"),u.classList.add("hidden"),w()}catch(e){u.classList.add("hidden"),a.error({title:"Error",message:e.message,position:"center"})}}function w(){const o=p.firstElementChild;if(!o)return;const s=o.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
